create table if not exists public."Users" (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  picture text,
  created_at timestamptz not null default now()
);

create table if not exists public."Interviews" (
  id bigint generated by default as identity primary key,
  interview_id uuid not null unique,
  jobPosition text,
  jobDescription text,
  duration text,
  type text,
  questionList jsonb,
  userEmail text not null,
  created_at timestamptz not null default now()
);

create table if not exists public."interview-feedback" (
  id bigint generated by default as identity primary key,
  interview_id uuid not null,
  userName text,
  userEmail text,
  feedback jsonb,
  recommended boolean not null default false,
  created_at timestamptz not null default now(),
  constraint interview_feedback_interview_id_fkey
    foreign key (interview_id)
    references public."Interviews" (interview_id)
    on delete cascade
);

create index if not exists idx_interviews_user_email
  on public."Interviews" (userEmail);

create index if not exists idx_feedback_interview_id
  on public."interview-feedback" (interview_id);
